config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get 'home' => 'static#home'
  get 'about' => 'static#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  # Default home page
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def webpage_title(page_title = '')
    base_title = "Ryhope Heritage Society"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= webpage_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="main-header">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#rhs-navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <%= link_to "Ryhope Heritage Society", home_path, class:"navbar-brand" %>
                <%= image_tag "logo.jpg",style:"width:50px;" %>
            </div>
            <div class="collapse navbar-collapse" id="rhs-navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "About", about_path %></li>
                    <li><%= link_to "Schedule", home_path %></li>
                    <li><%= link_to "Contact", home_path %></li>
                </ul>
            </div>
        </div>
    </nav>
  </div>
  <div class="main-content">
    <%= yield %>
  </div>
  <div class="main-footer">
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    <small class="copyright">&copy; Brian Ibinson 2015</small>
                </div>
                <div class="col-xs-6">
                    <div class="pull-right">
                        <ul class="list-inline" style="margin-bottom:3px">
                            <li><%= link_to icon("twitter"), home_path %></li>
                            <li><%= link_to icon("facebook"), "https://www.facebook.com/ryhopepicturesvids/" %></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
     </footer>
  </div>
</body>
</html>